"""add password to user

Revision ID: 993e04d6c882
Revises: 5530921942f3
Create Date: 2026-03-03 06:33:20.222078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '993e04d6c882'
down_revision: Union[str, Sequence[str], None] = '5530921942f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('Users', sa.Column('password_hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'password_hash')
    op.drop_column('Users', 'is_verified')
    # ### end Alembic commands ###
